name: Tenkai-API CI

on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'     
        required: true
        default: 'prd'
        type: choice
        options:
        - prd
        - dev
  banches:
    - main

jobs:
  build:
    environment: ${{ inputs.env }}
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PROJECT: ${{ secrets.PROJECT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Dockerize
        run: |
          gcloud auth configure-docker -q
          docker build . -t gcr.io/$PROJECT/python-hello-world:$GITHUB_REF_NAME -t gcr.io/$PROJECT/python-hello-world:latest
          docker push gcr.io/$PROJECT/python-hello-world:$GITHUB_REF_NAME
          docker push gcr.io/$PROJECT/python-hello-world:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PROJECT: ${{ secrets.PROJECT }}
    steps:
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: Deploy
        run: |
          gcloud run deploy python-hello-world \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --image=gcr.io/$PROJECT/python-hello-world:latest \
          --region=us-central1
