name: Test Matrix

on: 
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Trigger
        run: gh workflow run build-and-deploy.yaml -f environment=dev --ref develop
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
